### ISSUE TITLE
可以同步成功，但是使用ldap账号不能成功登陆禅道

### ISSUE THREAD

**Issue by tianxinliang123** [shynome/zentao-ldap#2]
好像是我的问题

**Comment by dawson2016** [comment]
我也不知道

**Comment by BrentHuang** [comment]
我这边也是登不了，你们搞定了没？
禅道11.5 stable版本

**Comment by BrentHuang** [comment]
连接是ok的，同步了0位用户，登录不了。

**Comment by shynome** [comment]
用这个 docker 版本试试 shynome/zentao:11.5@sha256:5633d52bd8175ec2e93c3f77d0fad1778f16fa5583493b69785d7dc9b6969386

我这边是好的话就没有啥理由和时间来管这个了, 需要你们的 pr 来修复这个问题

**Comment by shynome** [comment]
docker-compose.yml 文件示例
```yml
services:
  zentao:
    image: shynome/zentao:11.5@sha256:5633d52bd8175ec2e93c3f77d0fad1778f16fa5583493b69785d7dc9b6969386
    volumes: 
      - zentao:/app/zentaopms
    logging: { <<: *logging }
    deploy:
      endpoint_mode: dnsrr
      resources: { limits: { memory: 2G } }
```
